export interface DrillPromptInput {
  gameModelId: string;
  ageGroup: string;
  phase: string;
  zone: string;
  numbersMin: number;
  numbersMax: number;
  gkOptional?: boolean;
  goalsAvailable: number;
  spaceConstraint: string;
  durationMin?: number;
  
  // NEW: Required formation & level fields
  formationUsed: string;
  playerLevel: string;
  coachLevel: string;
}

/**
 * Main generator prompt for a single drill.
 * We keep it structured and JSON-only to make parsing robust.
 */
export function buildDrillPrompt(input: DrillPromptInput): string {
  const ctx = JSON.stringify(input, null, 2);

  return [
    "SYSTEM: You MUST output JSON matching the EXACT structure in the example below. Do NOT use old keys.",
    "",
    "════════════════════════════════════════════════════════════════════════",
    "⚠️  COPY THIS STRUCTURE EXACTLY - DO NOT DEVIATE  ⚠️",
    "════════════════════════════════════════════════════════════════════════",
    "",
    "REQUIRED JSON STRUCTURE (follow this pattern exactly):",
    "{",
    '  "organization": {',
    '    "setupSteps": ["Step 1...", "Step 2...", "Step 3...", "Step 4...", "Step 5...", "Step 6..."],',
    '    "area": {"lengthYards": 35, "widthYards": 25},',
    '    "rotation": "Who rotates when...",',
    '    "restarts": "How ball restarts...",',
    '    "scoring": "Scoring rules..."',
    '  },',
    '  "progressions": ["Progression 1", "Progression 2"],',
    '  "diagram": { ... },',
    "}",
    "",
    "⚠️  FORBIDDEN KEYS (DO NOT USE THESE): ⚠️",
    '- DO NOT use "diagramV1" (use "diagram" only)',
    '- DO NOT use "progression" (use "progressions" array only)',
    '- DO NOT use "organization" as string (MUST be object with setupSteps)',
    "",
    "════════════════════════════════════════════════════════════════════════",
    "",
    "INPUT CONSTRAINTS (age, formation, numbers must match these exactly):",
    ctx,
    "",
    "═══════════════════════════════════════════════════════════════",
    "⚠️ CRITICAL: Follow this PERFECT EXAMPLE structure EXACTLY ⚠️",
    "═══════════════════════════════════════════════════════════════",
    "",
    "EXAMPLE OUTPUT (copy this structure):",
    "```json",
    "{",
    '  "title": "4v4+GK Possession Game in Final Third",',
    '  "ageGroup": "U10",',
    '  "description": "Attackers keep possession to create chances. Defenders win ball and counter.",',
    '  "organization": {',
    '    "setupSteps": [',
    '      "Mark a 35x25 yard area with cones",',
    '      "Place two mini-goals on one end, 10 yards apart",',
    '      "Place one large goal on opposite end with GK",',
    '      "Split 9 players: 4 attackers, 4 defenders, 1 GK",',
    '      "Position attackers in 2-2 shape",',
    '      "Start with coach pass to attacker"',
    '    ],',
    '    "area": { "lengthYards": 35, "widthYards": 25, "notes": "Attacking third" },',
    '    "rotation": "After 2 goals: attackers→defenders→rest→attackers",',
    '    "restarts": "Coach passes to attacker after goal",',
    '    "scoring": "+1 per goal, +2 for one-touch finish"',
    '  },',
    '  "progressions": ["Add recovering defender", "Require 5 passes minimum"],',
    '  "diagram": { "pitch": {"variant": "HALF"}, "players": [], "goals": [] },',
    '  "numbersOnField": { "attackersOnField": 4, "defendersOnField": 4, "gkForDefend": true, "totalPlayersOnField": 9 }',
    "}",
    "```",
    "",
    "KEY RULES (follow the example above):",
    "1. organization MUST be an OBJECT with setupSteps, area, rotation, restarts, scoring",
    "2. Use 'diagram' NOT 'diagramV1'",
    "3. Use 'progressions' array NOT 'progression'",
    "4. All ages must match input.ageGroup",
    "5. Player counts must be consistent",
    "",
    "═══════════════════════════════════════════════════════════════",
    "CRITICAL: CLARITY + CONSISTENCY RULES",
    "═══════════════════════════════════════════════════════════════",
    "",
    "1) Use ONLY the schema keys provided below. Do NOT output alternate versions like:",
    "   - NO 'diagramV1' (use 'diagram' only)",
    "   - NO 'progression' (use 'progressions' only)",
    "   - NO nested json.json objects or duplicate containers",
    "",
    "2) Age consistency is MANDATORY:",
    "   - Every mention of age MUST equal input.ageGroup",
    "   - NEVER reference other age bands (no 'U12' anywhere if input is 'U10')",
    "   - Check description, organization, coachingPoints, constraints for age mentions",
    "",
    "3) Player counts MUST be consistent everywhere:",
    "   - numbersOnField.totalPlayersOnField MUST be within [input.numbersMin, input.numbersMax]",
    "   - description/organization.setupSteps/diagram must ALL reference the SAME on-field numbers",
    "   - Example: if you say '4v4+GK' in description, diagram must have exactly 4+4+1=9 players",
    "",
    "4) Provide EXACTLY ONE 'diagram' object (NOT 'diagramV1'):",
    "   - Use the canonical diagram schema below",
    "   - Do not duplicate with alternate keys",
    "",
    "5) Provide EXACTLY ONE 'progressions' array (NOT 'progression'):",
    "   - Must be an array of strings",
    "   - 2-4 progressions that build complexity",
    "",
    "6) Space + goals constraints are HARD:",
    "   - Use input.spaceConstraint to choose realistic dimensions",
    "   - Use input.goalsAvailable to set goalMode and scoring",
    "   - If goalsAvailable=0, goalMode='NONE'; if 1, goalMode='LARGE'; if 2+, goalMode='MINI2'",
    "",
    "7) Coach & player level are HARD:",
    "   - Use input.coachLevel to control instruction detail and language complexity",
    "   - Use input.playerLevel to control tactical complexity and decision-making demands",
    "",
    "8) Before outputting JSON, run this MANDATORY checklist:",
    "   ✓ Age mentions = input.ageGroup everywhere?",
    "   ✓ Player counts consistent (description = organization = diagram)?",
    "   ✓ Using 'diagram' (not 'diagramV1')?",
    "   ✓ Using 'progressions' array (not 'progression')?",
    "   ✓ Dimensions realistic for space constraint?",
    "   ✓ Restart/rotation rules crystal clear in organization.rotation?",
    "   ✓ Setup max 3 sentences?",
    "   ✓ Load structure explicit (e.g., '6 x 2:00 / 1:00 rest')?",
    "",
    "IMPORTANT INTERPRETATION RULES:",
    "- formationUsed is the EXACT formation (e.g., '4-3-3', '2-3-1') that MUST be used for role labels and team shape.",
    "- Use formationUsed to determine which roles (GK, CB, FB, WB, DM, CM, AM, W, ST, etc.) are most natural.",
    "- Role labels in the diagram and teamShape MUST align with formationUsed (e.g., 4-3-3 uses ST, LW, RW, not just generic 'forward').",
    "- numbersMin / numbersMax describe typical SESSION numbers, not on-field count for every rep.",
    "- For the drill itself, choose a realistic on-field game (e.g. 4v4+GK, 6v4+GK) that fits the topic and age.",
    "- gkOptional + goalsAvailable tell you whether to include a full GK and how many big goals / mini-goals.",
    "- spaceConstraint tells you how big the area is: FULL, HALF, THIRD, QUARTER.",
    "",
    "LEVEL-BASED CONSTRAINTS:",
    "- playerLevel (BEGINNER/INTERMEDIATE/ADVANCED) determines drill complexity:",
    "  * BEGINNER: Simple 1-2 touch patterns, clear roles, minimal decision-making, short sequences",
    "  * INTERMEDIATE: Combination play, 2-3 decisions per sequence, some tactical awareness",
    "  * ADVANCED: Complex patterns, multiple decisions, high tactical/technical demands, game-realistic chaos",
    "- coachLevel (GRASSROOTS/USSF_C/USSF_B_PLUS) determines coaching language and detail:",
    "  * GRASSROOTS: Simple language, focus on fun and fundamentals, minimal tactical jargon",
    "  * USSF_C: Moderate detail, introduce tactical concepts, clear progressions",
    "  * USSF_B_PLUS: Advanced tactical language, detailed coaching points, sophisticated progressions",
    "",
    "JSON OUTPUT FORMAT:",
    "Return ONLY a single JSON object with this exact structure (no markdown, no comments):",
    "{",
    '  "title": string,',
    '  "ageGroup": string,',
    '  "phase": string,',
    '  "zone": string,',
    '  "gameModelId": string,',
    '  "formationUsed": string,  // MUST match input.formationUsed exactly',
    '  "playerLevel": string,    // MUST match input.playerLevel exactly',
    '  "coachLevel": string,     // MUST match input.coachLevel exactly',
    '  "topic": string,',
    "",
    '  "numbers": { "min": number, "max": number },',
    '  "durationMin": number,',
    "",
    '  "description": string,  // Max 3 sentences describing what players do',
    "",
    '  "organization": {',
    '    "setupSteps": string[],  // 5-8 bullet steps, EACH STARTS WITH A VERB (Mark, Place, Split, Start, etc.)',
    '    "area": {',
    '      "lengthYards": number,',
    '      "widthYards": number,',
    '      "notes": string  // optional: e.g., "Use penalty area", "Half of center circle"',
    '    },',
    '    "rotation": string,  // WHO rotates WHEN, groups, reps (e.g., "Attackers become defenders after 2 goals, defenders rest")',
    '    "restarts": string,  // HOW the ball restarts (e.g., "Coach pass to AM", "GK throws to RB")',
    '    "scoring": string    // HOW to score + bonus points (e.g., "+1 for goal, +2 for one-touch finish")',
    '  },',
    "",
    '  "constraints": string[],',
    '  "progressions": string[],  // 2-4 progressions that build complexity',
    '  "coachingPoints": string[],',
    '  "psychTheme": string,',
    '  "equipment": string[],',
    "",
    '  "loadNotes": {',
    '    "structure": string,  // MUST be explicit like "6 x 2:00 / 1:00 rest (1:0.5)" or "8 x 90s / 90s rest (1:1)"',
    '    "rationale": string',
    '  },',
    "",
    '  "teamShape": {',
    '    "formation": string,',
    '    "attackRoles": [',
    '      { "role": string, "line": "last" | "back" | "middle" | "front", "side": "left" | "right" | "central" },',
    '      ...',
    "    ],",
    '    "defendRoles": [',
    '      { "role": string, "line": "last" | "back" | "middle" | "front", "side": "left" | "right" | "central" },',
    '      ...',
    "    ],",
    '    "notes": string',
    "  },",
    "",
    '  "numbersOnField": {',
    '    "attackersOnField": number,',
    '    "defendersOnField": number,',
    '    "neutralsOnField": number,',
    '    "gkForAttack": boolean,',
    '    "gkForDefend": boolean,',
    '    "totalPlayersOnField": number',
    "  },",
    "",
    '  "roleUsage": {',
    '    "activeAttackRoles": string[],',
    '    "activeDefendRoles": string[],',
    '    "activeNeutralRoles": string[],',
    '    "notes": string',
    "  },",
    "",
    '  "diagram": {  // ⚠️ Use "diagram" NOT "diagramV1"',
    '    "pitch": {',
    '      "variant": "FULL" | "HALF" | "THIRD" | "QUARTER",',
    '      "orientation": "HORIZONTAL",',
    '      "showZones": boolean,',
    '      "zones": {',
    '        "leftWide": boolean,',
    '        "leftHalfSpace": boolean,',
    '        "centralChannel": boolean,',
    '        "rightHalfSpace": boolean,',
    '        "rightWide": boolean',
    "      }",
    "    },",
    "",
    '    "players": [',
    '      {',
    '        "id": string,             // unique ID e.g. "A1", "D2", "N1"',
    '        "number": number,         // shirt number consistent with role (4/5 = CB, 2/3 = FB, 6 = DM, 7/11 = W, 9/10 = ST)',
    '        "team": "ATT" | "DEF" | "NEUTRAL",',
    '        "role": string,           // e.g. "GK", "RB", "LCB", "DM", "CM", "W", "ST"',
    '        "x": number,              // 0–100 as a percentage across the width of the pitch',
    '        "y": number,              // 0–100 as a percentage from bottom (0) to top (100) of the pitch',
    '        "relativePosition": string,',
    '        "facingAngle": number,    // 0 means attacking from bottom to top',
    '        "labelStyle": "number-and-role"',
    "      }",
    "      // ...more players",
    "    ],",
    "",
    '    "coach": {',
    '      "x": number,',
    '      "y": number,',
    '      "label": "Coach",',
    '      "note": string',
    "    },",
    "",
    '    "balls": any[],',
    '    "cones": any[],',
    '    "arrows": [',
    '      {',
    '        "from": { "playerId": string },',
    '        "to": { "playerId": string },',
    '        "type": "pass" | "run" | "press",',
    '        "style": "solid" | "dashed",',
    '        "weight": "normal" | "light"',
    "      }",
    "      // ...more arrows",
    "    ],",
    "",
    '    "areas": any[],',
    '    "labels": any[],',
    '    "goals": [',
    '      {',
    '        "id": string,',
    '        "type": "BIG" | "MINI",',
    '        "width": number,',
    '        "x": number,',
    '        "y": number,',
    '        "facingAngle": number,',
    '        "teamAttacks": "ATT" | "DEF" | "NEUTRAL"',
    "      }",
    "      // ...more goals if needed",
    "    ]",
    "  },",
    "",
    '  "goalMode": string,',
    '  "goalsAvailable": number,',
    '  "gkOptional": boolean',
    "}",
    "",
    "DIAGRAM & SPACING RULES:",
    "- Assume the ATTACKING team always attacks from bottom (y ~ 80) toward top (y ~ 10).",
    "- Use x from 0 to 100 (0 = left touchline, 100 = right touchline).",
    "- Use y from 0 to 100 (0 = bottom, 100 = top); keep players comfortably inside 10–90 unless the constraint demands otherwise.",
    "- Fullbacks (RB/LB) should be positioned OUTSIDE in the wide channels, not stuck in the half-spaces.",
    "- Center backs (RCB/LCB) should sit in the central channel or half-spaces on the same horizontal line.",
    "- The pivot/DM should be central, slightly ahead of the CBs.",
    "- Wingers should be in wide channels, higher than fullbacks.",
    "- Strikers should be central or half-space, highest up the pitch.",
    "- For pressing drills, DEF players should face down (facingAngle ~ 180) and start higher up the pitch relative to ATT.",
    "- Keep spacing realistic: do not cluster all players inside the box unless the drill is explicitly about box play.",
    "",
    "QUALITY & ALIGNMENT:",
    "- Make the drill clearly serve the topic in input.topic (if provided).",
    "- Match difficulty to input.ageGroup and input.playerLevel.",
    "- Use constraints and scoring to force the behavior you want (e.g. triggers to press, conditions to play through).",
    "- psychTheme should describe a mental skill: e.g. 'Composure & Scanning', 'Bravery to press', 'Communication & Leadership'.",
    "",
    "════════════════════════════════════════════════════════════════════════",
    "FINAL CHECKLIST BEFORE YOU RESPOND:",
    "════════════════════════════════════════════════════════════════════════",
    "1. Is 'organization' an OBJECT with setupSteps array? (NOT a string!)",
    "2. Am I using 'diagram' (NOT 'diagramV1')?",
    "3. Am I using 'progressions' array (NOT 'progression')?",
    "4. Do ALL age mentions equal " + input.ageGroup + "? (check organization, loadNotes, description)",
    "5. Are player counts consistent everywhere?",
    "",
    "OUTPUT RULES:",
    "- Return ONLY raw JSON (no markdown, no ```json wrapper, no explanations)",
    "- organization MUST be an object with setupSteps, area, rotation, restarts, scoring",
    "- Use 'diagram' not 'diagramV1', 'progressions' not 'progression'",
  ].join("\n");
}

/**
 * QA reviewer prompt: returns a JSON QA report with scores 1–5.
 */
export function buildQAReviewerPrompt(drill: any): string {
  const prettyDrill = JSON.stringify(drill, null, 2);

  return [
    "You are CoachAI-Reviewer, a UEFA A-license coach with expertise in sport psychology and sport science.",
    "",
    "You will receive a single youth soccer training drill in JSON under the key 'drill'.",
    "Your job is to review the drill for structure, clarity, realism, safety, constraints, and alignment with the game model and psychological theme.",
    "",
    "Respond ONLY with a JSON object of the form:",
    "{",
    '  "pass": boolean,',
    '  "scores": {',
    '    "structure": number,',
    '    "gameModel": number,',
    '    "psych": number,',
    '    "clarity": number,',
    '    "realism": number,',
    '    "constraints": number,',
    '    "safety": number',
    "  },",
    '  "summary": string,',
    '  "notes": string[]',
    "}",
    "",
    "Scoring scale (1–5):",
    "1 = unusable / fundamentally broken.",
    "2 = serious issues; major rewrite required.",
    "3 = usable with clear fixes.",
    "4 = strong.",
    "5 = excellent, model quality.",
    "",
    "CLARITY RUBRIC (critical for clarity score):",
    "Score 5 if:",
    "  ✓ Has organization.setupSteps with 5-8 actionable steps (each starts with verb)",
    "  ✓ Has organization.area with numeric lengthYards/widthYards",
    "  ✓ Has organization.rotation clearly stating who rotates when",
    "  ✓ Has organization.restarts stating how ball restarts",
    "  ✓ Has organization.scoring stating how to score",
    "  ✓ NO age mismatches (all age mentions = drill.ageGroup)",
    "  ✓ Player counts consistent (description, organization, diagram all match)",
    "  ✓ NO duplicate keys (diagramV1, progression)",
    "  ✓ Has ONLY 'diagram' (not 'diagramV1')",
    "  ✓ Has ONLY 'progressions' array (not 'progression')",
    "",
    "Score 3-4 if:",
    "  • Minor inconsistencies in player counts or age references",
    "  • organization.setupSteps exists but <5 or >8 items",
    "  • Missing some organization subfields but main structure present",
    "",
    "Score 1-2 if:",
    "  • Age mismatch (e.g., U12 mentioned in U10 drill)",
    "  • Player counts wildly inconsistent",
    "  • organization is string instead of object",
    "  • Has forbidden duplicate keys (diagramV1, progression)",
    "  • Missing critical organization fields",
    "",
    "Here is the drill JSON to review under 'drill':",
    prettyDrill
  ].join("\n");
}
